import logging
from typing import Any, Dict, List, Optional
from langchain_core.documents import Document
from tenacity import (
    before_sleep_log,
    retry,
    retry_if_exception_type,
    stop_after_attempt,
    wait_exponential,
)
from src.chains.factory import create_generator_chain
from src.state.state import GraphState

logger = logging.getLogger(__name__)


@retry(
    reraise=True,
    stop=stop_after_attempt(3),
    wait=wait_exponential(multiplier=1, min=0.5, max=3.0),
    retry=retry_if_exception_type(Exception),
    before_sleep=before_sleep_log(logger, logging.WARNING),
)
async def _invoke_generator_chain_with_retry(
    context: str, question: str, retry_notes: str
) -> str:
    generator_chain = create_generator_chain()
    return await generator_chain.ainvoke(
        {"context": context, "question": question, "retry_notes": retry_notes}
    )


def _build_retry_notes(state: GraphState) -> str:
    notes: List[str] = []

    hallucination_reasoning: Optional[str] = state.get("hallucination_reasoning")
    if hallucination_reasoning:
      
       
      constraint_message = (
            "DATA VALIDATION CONSTRAINT:\n"
            f"- Fact-check finding: {hallucination_reasoning}\n"
            "- Prohibited: Do NOT assert, assume, or reference the invalid claim cited above.\n"
            "- Required: Rely strictly on facts explicitly written in the context. "
            "If the text does not contain the answer, state that the information is missing. "
            "Do NOT explain this constraint, do NOT mention errors, and avoid background meta-talk."
        )
      notes.append(constraint_message)
        

    if not notes:
        return ""

    return "<retry_notes>\n" + "\n".join(f"- {note}" for note in notes) + "\n</retry_notes>"

async def generate_node(state: GraphState) -> Dict[str, Any]:
    logger.info("Executing async response generation...")

    question: str = state["question"]
    documents: List[Document] = state.get("documents", [])

    formatted_context: str = "\n\n---\n\n".join(
        f"Document [{idx + 1}]:\n{doc.page_content}"
        for idx, doc in enumerate(documents)
    )

    retry_notes: str = _build_retry_notes(state)
    is_retry: bool = bool(retry_notes)

    if is_retry:
        logger.info("Regenerating with prior grader reasoning injected: %s", retry_notes)

    generation: str = await _invoke_generator_chain_with_retry(
        context=formatted_context,
        question=question,
        retry_notes=retry_notes,
    )

    logger.info("Response successfully generated by LLM.")

    log_entry: Dict[str, Any] = {
        "node": "generate_node",
        "input_question": question,
        "context_doc_count": len(documents),
        "generated_char_length": len(generation),
        "generated_text": generation,
        "used_retry_notes": is_retry,
        "success": True,
    }

    return {
        "generation": generation,
        "audit_logs": [log_entry],
        "hallucination_reasoning": None,
    }