import logging
from typing import Any, Dict, List
from langchain_core.documents import Document
from tenacity import (
    before_sleep_log,
    retry,
    retry_if_exception_type,
    stop_after_attempt,
    wait_exponential,
)
from src.chains.factory import create_generator_chain
from src.state.state import GraphState

logger = logging.getLogger(__name__)


# Gecici model yukleme veya Ollama yanit gecikmelerine karsi ustel geri cekilmeli retry fonksiyonu
@retry(
    reraise=True,
    stop=stop_after_attempt(3),
    wait=wait_exponential(multiplier=1, min=0.5, max=3.0),
    retry=retry_if_exception_type(Exception),
    before_sleep=before_sleep_log(logger, logging.WARNING),
)
async def _invoke_generator_chain_with_retry(context: str, question: str) -> str:
    generator_chain = create_generator_chain()
    return await generator_chain.ainvoke(
        {"context": context, "question": question}
    )


async def generate_node(state: GraphState) -> Dict[str, Any]:
    # Kullanicinin orijinal niyetini ve format taleplerini koruyarak dogrulanmis baglamdan yanit uretir
    logger.info("Executing async response generation...")

    question: str = state["original_question"]
    documents: List[Document] = state.get("documents", [])

    # Dokuman parcalarini ayiricilar ile tek bir temiz metin bloguna donusturme
    formatted_context: str = "\n\n---\n\n".join(
        f"Document [{idx + 1}]:\n{doc.page_content}"
        for idx, doc in enumerate(documents)
    )

    # 3 basarisiz deneme sonunda hata yakalanmaz, fail-fast yaklasimiyla yukari firlatilir
    generation: str = await _invoke_generator_chain_with_retry(
        context=formatted_context,
        question=question,
    )

    logger.info("Response successfully generated by LLM.")

    log_entry: Dict[str, Any] = {
        "node": "generate_node",
        "input_question": question,
        "context_doc_count": len(documents),
        "generated_char_length": len(generation),
        "success": True,
    }

    return {
        "generation": generation,
        "audit_logs": [log_entry],
    }